version: "3"
services:
  nginx-web:
    image: nginx:alpine
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    restart: unless-stopped
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
    ports:
      - 80:80
      - 443:443
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
    networks:
      - webproxy
    logging:
      options:
        max-size: '4m'
        max-file: '10'

  nginx-gen:
    image: helder/docker-gen
    command: -notify "docker-label-sighup com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy" -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen
    restart: unless-stopped
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /srv/nginx-proxy/docker-gen/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    networks:
      - webproxy
    logging:
      options:
        max-size: '4m'
        max-file: '10'

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      - DEFAULT_EMAIL=youremail@example.com
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
    restart: unless-stopped
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - webproxy
    logging:
      options:
        max-size: '4m'
        max-file: '10'

networks:
  webproxy:
    external:
      name: webproxy

volumes:
  conf:
  vhost:
  html:
  certs:
